[platformio]
default_envs = esp8266
src_dir = .

[common]
framework = arduino
monitor_speed = 115200
lib_deps =
  gyverlibs/GyverHX711@^1.2
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.0
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
build_flags =
  -D HIVE_FW_VERSION=\"0.1.0\"
  -D MQTT_MAX_PACKET_SIZE=1024

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps =
  ${common.lib_deps}
  ESP8266WiFi
  ESP8266WebServer
  ESP8266HTTPUpdateServer
  LittleFS
lib_ldf_mode = deep+
build_flags =
  ${common.build_flags}
  -D HIVE_PLATFORM_ESP8266
  -I shared
build_src_filter =
  -<*>
  +<shared/>
  +<esp8266/src/>

[env:esp32]
platform = espressif32
board = esp32dev
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps =
  ${common.lib_deps}
  WiFi
  WiFiClientSecure
  WebServer
  Update
  LittleFS
build_flags =
  ${common.build_flags}
  -D HIVE_PLATFORM_ESP32
  -I shared
build_src_filter =
  -<*>
  +<shared/>
  +<esp32/src/>
